FROM golang:latest as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /let-go-web-repl

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /let-go-web-repl .
COPY wasm/index.html .
COPY wasm/index.js .
EXPOSE 80
ENTRYPOINT ["/root/let-go-web-repl"]