FROM golang:1.19 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o let-go-nrepl-server ./pkg/nrepl

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/let-go-nrepl-server .
EXPOSE 8080
CMD ["./let-go-nrepl-server"]