# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY wasm/package*.json ./

# Install any dependencies
RUN npm install

# Bundle app source
COPY wasm/ .

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Define environment variable
ENV NAME World

# Run index.js when the container launches
CMD ["node", "index.js"]